# Generated by Django 6.0.6 on 2026-07-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('overdue', 'Overdue')], default='active', max_length=10),
        ),
    ]
